//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1G5_PVFAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER
    {
        public string OrderID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string CustomerID { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual ORDER_LINE ORDER_LINE { get; set; }
    }
}
