//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1G5_PVFAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUPPLIES
    {
        public string MaterialID { get; set; }
        public string VendorID { get; set; }
        public decimal SupplyUnitPrice { get; set; }
    
        public virtual RAW_MATERIAL RAW_MATERIAL { get; set; }
        public virtual VENDOR VENDOR { get; set; }
    }
}
